# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8bQWKQXhM7yxM-TVrpm9sICbKCCQXDd
"""

import threading

string = ''

def input_thread():
  global string
  # Get input from user
  string = input('Enter a string: ')
#function to reverse the string 
def reverse_thread():
  global string
  print(string[::-1])


#function to capatalize the string
def capital_thread():
  global string
  print(string.upper())


#function to character in the string by two
def shift_thread():
  global string
  shifted_string = ''
  for c in string:
    shifted_string += chr(ord(c) + 2)
  print(shifted_string)

#create and start the threads
input_thread = threading.Thread(target=input_thread)
reverse_thread = threading.Thread(target=reverse_thread)
capital_thread = threading.Thread(target=capital_thread)
shift_thread = threading.Thread(target=shift_thread)

input_thread.start()

#wait for input thread to finish
input_thread.join()

#start the other threads
reverse_thread.start()
capital_thread.start()
shift_thread.start()

reverse_thread.join()
capital_thread.join()
shift_thread.join()